Attribute VB_Name = "Alignment"
Public ALIGNMENT_ALIGNMENT_GENERAL As String
Public ALIGNMENT_ALIGNMENT_CENTER As String
Public ALIGNMENT_ALIGNMENT_LEFT As String
Public ALIGNMENT_ALIGNMENT_RIGHT As String
Public ALIGNMENT_ALIGNMENT_FILL As String
Public ALIGNMENT_ALIGNMENT_JUSTIFY As String
Public ALIGNMENT_ALIGNMENT_CENTER_ACROSS_SELECTION As String
Public ALIGNMENT_ALIGNMENT_DISTRIBUTED As String
Public ALIGNMENT_ALIGNMENT_TOP As String
Public ALIGNMENT_ALIGNMENT_MIDDLE As String
Public ALIGNMENT_ALIGNMENT_BOTTOM As String
Public ALIGNMENT_TEXT_DIRECTION_CONTEXT As Long
Public ALIGNMENT_TEXT_DIRECTION_LEFT_TO_RIGHT As Long
Public ALIGNMENT_TEXT_DIRECTION_RIGHT_TO_LEFT As Long

Sub Initialize()
	ALIGNMENT_ALIGNMENT_GENERAL = "general"
	ALIGNMENT_ALIGNMENT_CENTER = "center"
	ALIGNMENT_ALIGNMENT_LEFT = "left"
	ALIGNMENT_ALIGNMENT_RIGHT = "right"
	ALIGNMENT_ALIGNMENT_FILL = "fill"
	ALIGNMENT_ALIGNMENT_JUSTIFY = "justify"
	ALIGNMENT_ALIGNMENT_CENTER_ACROSS_SELECTION = "center across selection"
	ALIGNMENT_ALIGNMENT_DISTRIBUTED = "distributed"
	ALIGNMENT_ALIGNMENT_TOP = "top"
	ALIGNMENT_ALIGNMENT_MIDDLE = "middle"
	ALIGNMENT_ALIGNMENT_BOTTOM = "bottom"
	ALIGNMENT_TEXT_DIRECTION_CONTEXT = 0
	ALIGNMENT_TEXT_DIRECTION_LEFT_TO_RIGHT = 1
	ALIGNMENT_TEXT_DIRECTION_RIGHT_TO_LEFT = 2
End Sub
