Attribute VB_Name = "Border"
Public BORDER_BORDER_NONE As Long
Public BORDER_BORDER_THIN As Long
Public BORDER_BORDER_MEDIUM As Long
Public BORDER_BORDER_DASHED As Long
Public BORDER_BORDER_DOTTED As Long
Public BORDER_BORDER_THICK As Long
Public BORDER_BORDER_DOUBLE As Long
Public BORDER_BORDER_HAIR As Long
Public BORDER_BORDER_MEDIUM_DASHED As Long
Public BORDER_BORDER_DASH_DOT As Long
Public BORDER_BORDER_MEDIUM_DASH_DOT As Long
Public BORDER_BORDER_DASH_DOT_DOT As Long
Public BORDER_BORDER_MEDIUM_DASH_DOT_DOT As Long
Public BORDER_BORDER_SLANTED_DASH_DOT As Long

Sub Initialize()
	BORDER_BORDER_NONE = 0
	BORDER_BORDER_THIN = 1
	BORDER_BORDER_MEDIUM = 2
	BORDER_BORDER_DASHED = 3
	BORDER_BORDER_DOTTED = 4
	BORDER_BORDER_THICK = 5
	BORDER_BORDER_DOUBLE = 6
	BORDER_BORDER_HAIR = 7
	BORDER_BORDER_MEDIUM_DASHED = 8
	BORDER_BORDER_DASH_DOT = 9
	BORDER_BORDER_MEDIUM_DASH_DOT = 10
	BORDER_BORDER_DASH_DOT_DOT = 11
	BORDER_BORDER_MEDIUM_DASH_DOT_DOT = 12
	BORDER_BORDER_SLANTED_DASH_DOT = 13
End Sub
