Attribute VB_Name = "Color"
Public COLOR_TRANSPARENT As Long			
Public COLOR_ALICEBLUE As Long			
Public COLOR_ANTIQUEWHITE As Long			
Public COLOR_AQUA As Long			
Public COLOR_AQUAMARINE As Long			
Public COLOR_AZURE As Long			
Public COLOR_BEIGE As Long			
Public COLOR_BISQUE As Long			
Public COLOR_BLACK As Long			
Public COLOR_BLANCHEDALMOND As Long			
Public COLOR_BLUE As Long			
Public COLOR_BLUEVIOLET As Long			
Public COLOR_BROWN As Long			
Public COLOR_BURLYWOOD As Long			
Public COLOR_CADETBLUE As Long			
Public COLOR_CHARTREUSE As Long			
Public COLOR_CHOCOLATE As Long			
Public COLOR_CORAL As Long			
Public COLOR_CORNFLOWERBLUE As Long			
Public COLOR_CORNSILK As Long			
Public COLOR_CRIMSON As Long			
Public COLOR_CYAN As Long			
Public COLOR_DARKBLUE As Long			
Public COLOR_DARKCYAN As Long			
Public COLOR_DARKGOLDENROD As Long			
Public COLOR_DARKGRAY As Long			
Public COLOR_DARKGREEN As Long			
Public COLOR_DARKKHAKI As Long			
Public COLOR_DARKMAGENTA As Long			
Public COLOR_DARKOLIVEGREEN As Long			
Public COLOR_DARKORANGE As Long			
Public COLOR_DARKORCHID As Long			
Public COLOR_DARKRED As Long			
Public COLOR_DARKSALMON As Long			
Public COLOR_DARKSEAGREEN As Long			
Public COLOR_DARKSLATEBLUE As Long			
Public COLOR_DARKSLATEGRAY As Long			
Public COLOR_DARKTURQUOISE As Long			
Public COLOR_DARKVIOLET As Long			
Public COLOR_DEEPPINK As Long			
Public COLOR_DEEPSKYBLUE As Long			
Public COLOR_DIMGRAY As Long			
Public COLOR_DODGERBLUE As Long			
Public COLOR_FIREBRICK As Long			
Public COLOR_FLORALWHITE As Long			
Public COLOR_FORESTGREEN As Long			
Public COLOR_FUCHSIA As Long			
Public COLOR_GAINSBORO As Long			
Public COLOR_GHOSTWHITE As Long			
Public COLOR_GOLD As Long			
Public COLOR_GOLDENROD As Long			
Public COLOR_GRAY As Long			
Public COLOR_GREEN As Long			
Public COLOR_GREENYELLOW As Long			
Public COLOR_HONEYDEW As Long			
Public COLOR_HOTPINK As Long			
Public COLOR_INDIANRED As Long			
Public COLOR_INDIGO As Long			
Public COLOR_IVORY As Long			
Public COLOR_KHAKI As Long			
Public COLOR_LAVENDER As Long			
Public COLOR_LAVENDERBLUSH As Long			
Public COLOR_LAWNGREEN As Long			
Public COLOR_LEMONCHIFFON As Long			
Public COLOR_LIGHTBLUE As Long			
Public COLOR_LIGHTCORAL As Long			
Public COLOR_LIGHTCYAN As Long			
Public COLOR_LIGHTGOLDENRODYELLOW As Long			
Public COLOR_LIGHTGREEN As Long			
Public COLOR_LIGHTGRAY As Long			
Public COLOR_LIGHTPINK As Long			
Public COLOR_LIGHTSALMON As Long			
Public COLOR_LIGHTSEAGREEN As Long			
Public COLOR_LIGHTSKYBLUE As Long			
Public COLOR_LIGHTSLATEGRAY As Long			
Public COLOR_LIGHTSTEELBLUE As Long			
Public COLOR_LIGHTYELLOW As Long			
Public COLOR_LIME As Long			
Public COLOR_LIMEGREEN As Long			
Public COLOR_LINEN As Long			
Public COLOR_MAGENTA As Long			
Public COLOR_MAROON As Long			
Public COLOR_MEDIUMAQUAMARINE As Long			
Public COLOR_MEDIUMBLUE As Long			
Public COLOR_MEDIUMORCHID As Long			
Public COLOR_MEDIUMPURPLE As Long			
Public COLOR_MEDIUMSEAGREEN As Long			
Public COLOR_MEDIUMSLATEBLUE As Long			
Public COLOR_MEDIUMSPRINGGREEN As Long			
Public COLOR_MEDIUMTURQUOISE As Long			
Public COLOR_MEDIUMVIOLETRED As Long			
Public COLOR_MIDNIGHTBLUE As Long			
Public COLOR_MINTCREAM As Long			
Public COLOR_MISTYROSE As Long			
Public COLOR_MOCCASIN As Long			
Public COLOR_NAVAJOWHITE As Long			
Public COLOR_NAVY As Long			
Public COLOR_OLDLACE As Long			
Public COLOR_OLIVE As Long			
Public COLOR_OLIVEDRAB As Long			
Public COLOR_ORANGE As Long			
Public COLOR_ORANGERED As Long			
Public COLOR_ORCHID As Long			
Public COLOR_PALEGOLDENROD As Long			
Public COLOR_PALEGREEN As Long			
Public COLOR_PALETURQUOISE As Long			
Public COLOR_PALEVIOLETRED As Long			
Public COLOR_PAPAYAWHIP As Long			
Public COLOR_PEACHPUFF As Long			
Public COLOR_PERU As Long			
Public COLOR_PINK As Long			
Public COLOR_PLUM As Long			
Public COLOR_POWDERBLUE As Long			
Public COLOR_PURPLE As Long			
Public COLOR_RED As Long			
Public COLOR_ROSYBROWN As Long			
Public COLOR_ROYALBLUE As Long			
Public COLOR_SADDLEBROWN As Long			
Public COLOR_SALMON As Long			
Public COLOR_SANDYBROWN As Long			
Public COLOR_SEAGREEN As Long			
Public COLOR_SEASHELL As Long			
Public COLOR_SIENNA As Long			
Public COLOR_SILVER As Long			
Public COLOR_SKYBLUE As Long			
Public COLOR_SLATEBLUE As Long			
Public COLOR_SLATEGRAY As Long			
Public COLOR_SNOW As Long			
Public COLOR_SPRINGGREEN As Long			
Public COLOR_STEELBLUE As Long			
Public COLOR_TAN As Long			
Public COLOR_TEAL As Long			
Public COLOR_THISTLE As Long			
Public COLOR_TOMATO As Long			
Public COLOR_TURQUOISE As Long			
Public COLOR_VIOLET As Long			
Public COLOR_WHEAT As Long			
Public COLOR_WHITE As Long			
Public COLOR_WHITESMOKE As Long			
Public COLOR_YELLOW As Long			
Public COLOR_YELLOWGREEN As Long			
			
Sub Initialize()
	COLOR_ALICEBLUE 	=	 &hfffff8f0
	COLOR_ANTIQUEWHITE 	=	 &hffd7ebfa
	COLOR_AQUA 	=	 &hffffff00
	COLOR_AQUAMARINE 	=	 &hffd4ff7f
	COLOR_AZURE 	=	 &hfffffff0
	COLOR_BEIGE 	=	 &hffdcf5f5
	COLOR_BISQUE 	=	 &hffc4e4ff
	COLOR_BLACK 	=	 &hff000000
	COLOR_BLANCHEDALMOND 	=	 &hffcdebff
	COLOR_BLUE 	=	 &hffff0000
	COLOR_BLUEVIOLET 	=	 &hffe22b8a
	COLOR_BROWN 	=	 &hff2a2aa5
	COLOR_BURLYWOOD 	=	 &hff87b8de
	COLOR_CADETBLUE 	=	 &hffa09e5f
	COLOR_CHARTREUSE 	=	 &hff00ff7f
	COLOR_CHOCOLATE 	=	 &hff1e69d2
	COLOR_CORAL 	=	 &hff507fff
	COLOR_CORNFLOWERBLUE 	=	 &hffed9564
	COLOR_CORNSILK 	=	 &hffdcf8ff
	COLOR_CRIMSON 	=	 &hff3c14dc
	COLOR_CYAN 	=	 &hffffff00
	COLOR_DARKBLUE 	=	 &hff8b0000
	COLOR_DARKCYAN 	=	 &hff8b8b00
	COLOR_DARKGOLDENROD 	=	 &hff0b86b8
	COLOR_DARKGRAY 	=	 &hffa9a9a9
	COLOR_DARKGREEN 	=	 &hff006400
	COLOR_DARKKHAKI 	=	 &hff6bb7bd
	COLOR_DARKMAGENTA 	=	 &hff8b008b
	COLOR_DARKOLIVEGREEN 	=	 &hff2f6b55
	COLOR_DARKORANGE 	=	 &hff008cff
	COLOR_DARKORCHID 	=	 &hffcc3299
	COLOR_DARKRED 	=	 &hff00008b
	COLOR_DARKSALMON 	=	 &hff7a96e9
	COLOR_DARKSEAGREEN 	=	 &hff8bbc8f
	COLOR_DARKSLATEBLUE 	=	 &hff8b3d48
	COLOR_DARKSLATEGRAY 	=	 &hff4f4f2f
	COLOR_DARKTURQUOISE 	=	 &hffd1ce00
	COLOR_DARKVIOLET 	=	 &hffd30094
	COLOR_DEEPPINK 	=	 &hff9314ff
	COLOR_DEEPSKYBLUE 	=	 &hffffbf00
	COLOR_DIMGRAY 	=	 &hff696969
	COLOR_DODGERBLUE 	=	 &hffff901e
	COLOR_FIREBRICK 	=	 &hff2222b2
	COLOR_FLORALWHITE 	=	 &hfff0faff
	COLOR_FORESTGREEN 	=	 &hff228b22
	COLOR_FUCHSIA 	=	 &hffff00ff
	COLOR_GAINSBORO 	=	 &hffdcdcdc
	COLOR_GHOSTWHITE 	=	 &hfffff8f8
	COLOR_GOLD 	=	 &hff00d7ff
	COLOR_GOLDENROD 	=	 &hff20a5da
	COLOR_GRAY 	=	 &hff808080
	COLOR_GREEN 	=	 &hff008000
	COLOR_GREENYELLOW 	=	 &hff2fffad
	COLOR_HONEYDEW 	=	 &hfff0fff0
	COLOR_HOTPINK 	=	 &hffb469ff
	COLOR_INDIANRED 	=	 &hff5c5ccd
	COLOR_INDIGO 	=	 &hff82004b
	COLOR_IVORY 	=	 &hfff0ffff
	COLOR_KHAKI 	=	 &hff8ce6f0
	COLOR_LAVENDER 	=	 &hfffae6e6
	COLOR_LAVENDERBLUSH 	=	 &hfff5f0ff
	COLOR_LAWNGREEN 	=	 &hff00fc7c
	COLOR_LEMONCHIFFON 	=	 &hffcdfaff
	COLOR_LIGHTBLUE 	=	 &hffe6d8ad
	COLOR_LIGHTCORAL 	=	 &hff8080f0
	COLOR_LIGHTCYAN 	=	 &hffffffe0
	COLOR_LIGHTGOLDENRODYELLOW 	=	 &hffd2fafa
	COLOR_LIGHTGREEN 	=	 &hff90ee90
	COLOR_LIGHTGRAY 	=	 &hffd3d3d3
	COLOR_LIGHTPINK 	=	 &hffc1b6ff
	COLOR_LIGHTSALMON 	=	 &hff7aa0ff
	COLOR_LIGHTSEAGREEN 	=	 &hffaab220
	COLOR_LIGHTSKYBLUE 	=	 &hffface87
	COLOR_LIGHTSLATEGRAY 	=	 &hff998877
	COLOR_LIGHTSTEELBLUE 	=	 &hffdec4b0
	COLOR_LIGHTYELLOW 	=	 &hffe0ffff
	COLOR_LIME 	=	 &hff00ff00
	COLOR_LIMEGREEN 	=	 &hff32cd32
	COLOR_LINEN 	=	 &hffe6f0fa
	COLOR_MAGENTA 	=	 &hffff00ff
	COLOR_MAROON 	=	 &hff000080
	COLOR_MEDIUMAQUAMARINE 	=	 &hffaacd66
	COLOR_MEDIUMBLUE 	=	 &hffcd0000
	COLOR_MEDIUMORCHID 	=	 &hffd355ba
	COLOR_MEDIUMPURPLE 	=	 &hffdb7093
	COLOR_MEDIUMSEAGREEN 	=	 &hff71b33c
	COLOR_MEDIUMSLATEBLUE 	=	 &hffee687b
	COLOR_MEDIUMSPRINGGREEN 	=	 &hff9afa00
	COLOR_MEDIUMTURQUOISE 	=	 &hffccd148
	COLOR_MEDIUMVIOLETRED 	=	 &hff8515c7
	COLOR_MIDNIGHTBLUE 	=	 &hff701919
	COLOR_MINTCREAM 	=	 &hfffafff5
	COLOR_MISTYROSE 	=	 &hffe1e4ff
	COLOR_MOCCASIN 	=	 &hffb5e4ff
	COLOR_NAVAJOWHITE 	=	 &hffaddeff
	COLOR_NAVY 	=	 &hff800000
	COLOR_OLDLACE 	=	 &hffe6f5fd
	COLOR_OLIVE 	=	 &hff008080
	COLOR_OLIVEDRAB 	=	 &hff238e6b
	COLOR_ORANGE 	=	 &hff00a5ff
	COLOR_ORANGERED 	=	 &hff0045ff
	COLOR_ORCHID 	=	 &hffd670da
	COLOR_PALEGOLDENROD 	=	 &hffaae8ee
	COLOR_PALEGREEN 	=	 &hff98fb98
	COLOR_PALETURQUOISE 	=	 &hffeeeeaf
	COLOR_PALEVIOLETRED 	=	 &hff9370db
	COLOR_PAPAYAWHIP 	=	 &hffd5efff
	COLOR_PEACHPUFF 	=	 &hffb9daff
	COLOR_PERU 	=	 &hff3f85cd
	COLOR_PINK 	=	 &hffcbc0ff
	COLOR_PLUM 	=	 &hffdda0dd
	COLOR_POWDERBLUE 	=	 &hffe6e0b0
	COLOR_PURPLE 	=	 &hff800080
	COLOR_RED 	=	 &hff0000ff
	COLOR_ROSYBROWN 	=	 &hff8f8fbc
	COLOR_ROYALBLUE 	=	 &hffe16941
	COLOR_SADDLEBROWN 	=	 &hff13458b
	COLOR_SALMON 	=	 &hff7280fa
	COLOR_SANDYBROWN 	=	 &hff60a4f4
	COLOR_SEAGREEN 	=	 &hff578b2e
	COLOR_SEASHELL 	=	 &hffeef5ff
	COLOR_SIENNA 	=	 &hff2d52a0
	COLOR_SILVER 	=	 &hffc0c0c0
	COLOR_SKYBLUE 	=	 &hffebce87
	COLOR_SLATEBLUE 	=	 &hffcd5a6a
	COLOR_SLATEGRAY 	=	 &hff908070
	COLOR_SNOW 	=	 &hfffafaff
	COLOR_SPRINGGREEN 	=	 &hff7fff00
	COLOR_STEELBLUE 	=	 &hffb48246
	COLOR_TAN 	=	 &hff8cb4d2
	COLOR_TEAL 	=	 &hff808000
	COLOR_THISTLE 	=	 &hffd8bfd8
	COLOR_TOMATO 	=	 &hff4763ff
	COLOR_TURQUOISE 	=	 &hffd0e040
	COLOR_VIOLET 	=	 &hffee82ee
	COLOR_WHEAT 	=	 &hffb3def5
	COLOR_WHITE 	=	 &hffffffff
	COLOR_WHITESMOKE 	=	 &hfff5f5f5
	COLOR_YELLOW 	=	 &hff00ffff
	COLOR_YELLOWGREEN 	=	 &hff32cd9a
End Sub		
