Attribute VB_Name = "DataValidator"
Public DATAVALIDATOR_VALIDATE_ANY_VALUE As Long
Public DATAVALIDATOR_VALIDATE_WHOLE_NUMBER As Long
Public DATAVALIDATOR_VALIDATE_DECIMAL As Long
Public DATAVALIDATOR_VALIDATE_LIST As Long
Public DATAVALIDATOR_VALIDATE_DATE As Long
Public DATAVALIDATOR_VALIDATE_TIME As Long
Public DATAVALIDATOR_VALIDATE_TEXT_LENGTH As Long
Public DATAVALIDATOR_VALIDATE_CUSTOM As Long
Public DATAVALIDATOR_OPERATOR_BETWEEN As Long
Public DATAVALIDATOR_OPERATOR_NOT_BETWEEN As Long
Public DATAVALIDATOR_OPERATOR_EQUAL_TO As Long
Public DATAVALIDATOR_OPERATOR_NOT_EQUAL_TO As Long
Public DATAVALIDATOR_OPERATOR_GREATER_THAN As Long
Public DATAVALIDATOR_OPERATOR_LESS_THAN As Long
Public DATAVALIDATOR_OPERATOR_GREATER_THAN_OR_EQUAL_TO As Long
Public DATAVALIDATOR_OPERATOR_LESS_THAN_OR_EQUAL_TO As Long
Public DATAVALIDATOR_ERROR_STOP As Long
Public DATAVALIDATOR_ERROR_WARNING As Long
Public DATAVALIDATOR_ERROR_INFO As Long

Sub Initialize()
	DATAVALIDATOR_VALIDATE_ANY_VALUE = 0
	DATAVALIDATOR_VALIDATE_WHOLE_NUMBER = 1
	DATAVALIDATOR_VALIDATE_DECIMAL = 2
	DATAVALIDATOR_VALIDATE_LIST = 3
	DATAVALIDATOR_VALIDATE_DATE = 4
	DATAVALIDATOR_VALIDATE_TIME = 5
	DATAVALIDATOR_VALIDATE_TEXT_LENGTH = 6
	DATAVALIDATOR_VALIDATE_CUSTOM = 7
	DATAVALIDATOR_OPERATOR_BETWEEN = 0
	DATAVALIDATOR_OPERATOR_NOT_BETWEEN = 1
	DATAVALIDATOR_OPERATOR_EQUAL_TO = 2
	DATAVALIDATOR_OPERATOR_NOT_EQUAL_TO = 3
	DATAVALIDATOR_OPERATOR_GREATER_THAN = 4
	DATAVALIDATOR_OPERATOR_LESS_THAN = 5
	DATAVALIDATOR_OPERATOR_GREATER_THAN_OR_EQUAL_TO = 6
	DATAVALIDATOR_OPERATOR_LESS_THAN_OR_EQUAL_TO = 7
	DATAVALIDATOR_ERROR_STOP = 0
	DATAVALIDATOR_ERROR_WARNING = 1
	DATAVALIDATOR_ERROR_INFO = 2
End Sub
