Attribute VB_Name = "DataGroup"
Public DATAGROUP_GROUP_BY_ROWS As Long
Public DATAGROUP_GROUP_BY_COLUMNS As Long

Sub Initialize()
	DATAGROUP_GROUP_BY_ROWS = 0
	DATAGROUP_GROUP_BY_COLUMNS = 1
End Sub
