Attribute VB_Name = "FillFormat"
Public FILLFORMAT_PATTERN_NONE As Long
Public FILLFORMAT_PATTERN_SOLID As Long
Public FILLFORMAT_PATTERN_5_PERCENT As Long
Public FILLFORMAT_PATTERN_50_PERCENT As Long
Public FILLFORMAT_PATTERN_LIGHT_DOWNWARD_DIAGONAL As Long
Public FILLFORMAT_PATTERN_LIGHT_VERTICAL As Long
Public FILLFORMAT_PATTERN_DASHED_DOWNWARD_DIAGONAL As Long
Public FILLFORMAT_PATTERN_ZIG_ZAG As Long
Public FILLFORMAT_PATTERN_DIVOT As Long
Public FILLFORMAT_PATTERN_SMALL_GRID As Long
Public FILLFORMAT_PATTERN_10_PERCENT As Long
Public FILLFORMAT_PATTERN_60_PERCENT As Long
Public FILLFORMAT_PATTERN_LIGHT_UPWARD_DIAGONAL As Long
Public FILLFORMAT_PATTERN_LIGHT_HORIZONTAL As Long
Public FILLFORMAT_PATTERN_DASHED_UPWARD_DIAGONAL As Long
Public FILLFORMAT_PATTERN_WAVE As Long
Public FILLFORMAT_PATTERN_DOTTED_GRID As Long
Public FILLFORMAT_PATTERN_LARGE_GRID As Long
Public FILLFORMAT_PATTERN_20_PERCENT As Long
Public FILLFORMAT_PATTERN_70_PERCENT As Long
Public FILLFORMAT_PATTERN_DARK_DOWNWARD_DIAGONAL As Long
Public FILLFORMAT_PATTERN_NARROW_VERTICAL As Long
Public FILLFORMAT_PATTERN_DASHED_HORIZONTAL As Long
Public FILLFORMAT_PATTERN_DIAGONAL_BRICK As Long
Public FILLFORMAT_PATTERN_DOTTED_DIAMOND As Long
Public FILLFORMAT_PATTERN_SMALL_CHECKER_BOARD As Long
Public FILLFORMAT_PATTERN_25_PERCENT As Long
Public FILLFORMAT_PATTERN_75_PERCENT As Long
Public FILLFORMAT_PATTERN_DARK_UPWARD_DIAGONAL As Long
Public FILLFORMAT_PATTERN_NARROW_HORIZONTAL As Long
Public FILLFORMAT_PATTERN_DASHED_VERTICAL As Long
Public FILLFORMAT_PATTERN_HORIZONTAL_BRICK As Long
Public FILLFORMAT_PATTERN_SHINGLE As Long
Public FILLFORMAT_PATTERN_LARGE_CHECKER_BOARD As Long
Public FILLFORMAT_PATTERN_30_PERCENT As Long
Public FILLFORMAT_PATTERN_80_PERCENT As Long
Public FILLFORMAT_PATTERN_WIDE_DOWNWARD_DIAGONAL As Long
Public FILLFORMAT_PATTERN_DARK_VERTICAL As Long
Public FILLFORMAT_PATTERN_SMALL_CONFETTI As Long
Public FILLFORMAT_PATTERN_WEAVE As Long
Public FILLFORMAT_PATTERN_TRELLIS As Long
Public FILLFORMAT_PATTERN_OUTLINED_DIAMOND As Long
Public FILLFORMAT_PATTERN_40_PERCENT As Long
Public FILLFORMAT_PATTERN_90_PERCENT As Long
Public FILLFORMAT_PATTERN_WIDE_UPWARD_DIAGONAL As Long
Public FILLFORMAT_PATTERN_DARK_HORIZONTAL As Long
Public FILLFORMAT_PATTERN_LARGE_CONFETTI As Long
Public FILLFORMAT_PATTERN_PLAID As Long
Public FILLFORMAT_PATTERN_SPHERE As Long
Public FILLFORMAT_PATTERN_SOLID_DIAMOND As Long
Public FILLFORMAT_GRADIENT_FILL_DEFAULT As Long
Public FILLFORMAT_GRADIENT_FILL_EARLY_SUNSET As Long
Public FILLFORMAT_GGRADIENT_FILL_LATE_SUNSET As Long
Public FILLFORMAT_GRADIENT_FILL_NIGHTFALL As Long
Public FILLFORMAT_GRADIENT_FILL_DAYBREAK As Long
Public FILLFORMAT_GRADIENT_FILL_HORIZON As Long
Public FILLFORMAT_GRADIENT_FILL_DESERT As Long
Public FILLFORMAT_GRADIENT_FILL_OCEAN As Long
Public FILLFORMAT_GRADIENT_FILL_CALM_WATER As Long
Public FILLFORMAT_GRADIENT_FILL_FIRE As Long
Public FILLFORMAT_GRADIENT_FILL_FOG As Long
Public FILLFORMAT_GRADIENT_FILL_MOSS As Long
Public FILLFORMAT_GRADIENT_FILL_PEACOCK As Long
Public FILLFORMAT_GRADIENT_FILL_WHEAT As Long
Public FILLFORMAT_GRADIENT_FILL_PARCHMENT As Long
Public FILLFORMAT_GRADIENT_FILL_MAHOGANY As Long
Public FILLFORMAT_GRADIENT_FILL_RAINBOW As Long
Public FILLFORMAT_GRADIENT_FILL_RAINBOW_II As Long
Public FILLFORMAT_GRADIENT_FILL_GOLD As Long
Public FILLFORMAT_GRADIENT_FILL_GOLD_IIAs Long
Public FILLFORMAT_GRADIENT_FILL_BRASS As Long
Public FILLFORMAT_GRADIENT_FILL_CHROME As Long
Public FILLFORMAT_GRADIENT_FILL_CHROME_II As Long
Public FILLFORMAT_GRADIENT_FILL_SILVER As Long
Public FILLFORMAT_GRADIENT_FILL_SAPPHIRE As Long
Public FILLFORMAT_GRADIENT_TYPE_LINEAR As Long
Public FILLFORMAT_GRADIENT_TYPE_RADIAL As Long
Public FILLFORMAT_GRADIENT_TYPE_RECTANGULAR As Long
Public FILLFORMAT_GRADIENT_TYPE_PATH As Long
Public FILLFORMAT_GRADIENT_DIRECTION_LINEAR_DIAGONAL_45_DEGREES As Long
Public FILLFORMAT_GRADIENT_DIRECTION_LINEAR_DOWN_90_DEGREES As Long
Public FILLFORMAT_GRADIENT_DIRECTION_LINEAR_DIAGONAL_135_DEGREES As Long
Public FILLFORMAT_GRADIENT_DIRECTION_LINEAR_RIGHT_0_DEGREES As Long
Public FILLFORMAT_GRADIENT_DIRECTION_LINEAR_LEFT_180_DEGREES As Long
Public FILLFORMAT_GRADIENT_DIRECTION_LINEAR_DIAGONAL_315_DEGREES As Long
Public FILLFORMAT_GRADIENT_DIRECTION_LINEAR_UP_270_DEGREES As Long
Public FILLFORMAT_GRADIENT_DIRECTION_LINEAR_DIAGONAL_225_DEGREES As Long
Public FILLFORMAT_GRADIENT_DIRECTION_FROM_CORNER_UPPER_LEFT_TO_BOTTOM_RIGHT As Long
Public FILLFORMAT_GRADIENT_DIRECTION_FROM_CORNER_UPPER_RIGHT_TO_BOTTOM_LEFT As Long
Public FILLFORMAT_GRADIENT_DIRECTION_FROM_CENTER As Long
Public FILLFORMAT_GRADIENT_DIRECTION_FROM_CORNER_BOTTOM_LEFT_TO_UPPER_RIGHT As Long
Public FILLFORMAT_GRADIENT_DIRECTION_FROM_CORNER_BOTTOM_RIGHT_TO_UPPER_LEFT As Long
Public FILLFORMAT_TEXTURE_PAPYRUS As Long
Public FILLFORMAT_TEXTURE_CANVAS As Long
Public FILLFORMAT_TEXTURE_DENIM As Long
Public FILLFORMAT_TEXTURE_WOVEN_MAT As Long
Public FILLFORMAT_TEXTURE_WATER_DROPLETS As Long
Public FILLFORMAT_TEXTURE_PAPER_BAG As Long
Public FILLFORMAT_TEXTURE_FISH_FOSIL As Long
Public FILLFORMAT_TEXTURE_SAND As Long
Public FILLFORMAT_TEXTURE_GREEN_MARBLE As Long
Public FILLFORMAT_TEXTURE_WHITE_MARBLE As Long
Public FILLFORMAT_TEXTURE_BROWN_MARBLE As Long
Public FILLFORMAT_TEXTURE_GRANITE As Long
Public FILLFORMAT_TEXTURE_NEWSPRINT As Long
Public FILLFORMAT_TEXTURE_RECYCLED_PAPER As Long
Public FILLFORMAT_TEXTURE_PARCHMENT As Long
Public FILLFORMAT_TEXTURE_STATIONERY As Long
Public FILLFORMAT_TEXTURE_BLUE_TISSUE_PAPER As Long
Public FILLFORMAT_TEXTURE_PINK_TISSUE_PAPER As Long
Public FILLFORMAT_TEXTURE_PURPLE_MESH As Long
Public FILLFORMAT_TEXTURE_BOUQUET As Long
Public FILLFORMAT_TEXTURE_CORK As Long
Public FILLFORMAT_TEXTURE_WALNUT As Long
Public FILLFORMAT_TEXTURE_OAK As Long
Public FILLFORMAT_TEXTURE_MEDIUM_WOOD As Long
Public FILLFORMAT_TILING_ALIGNMENT_TOP_LEFT As String
Public FILLFORMAT_TILING_ALIGNMENT_TOP As String
Public FILLFORMAT_TILING_ALIGNMENT_TOP_RIGHT As String
Public FILLFORMAT_TILING_ALIGNMENT_LEFT As String
Public FILLFORMAT_TILING_ALIGNMENT_CENTER As String
Public FILLFORMAT_TILING_ALIGNMENT_RIGHT As String
Public FILLFORMAT_TILING_ALIGNMENT_BOTTOM_LEFT As String
Public FILLFORMAT_TILING_ALIGNMENT_BOTTOM As String
Public FILLFORMAT_TILING_ALIGNMENT_BOTTOM_RIGHT As String
Public FILLFORMAT_TILING_MIRROR_TYPE_NONE As String
Public FILLFORMAT_TILING_MIRROR_TYPE_HORIZONTAL As String
Public FILLFORMAT_TILING_MIRROR_TYPE_VERTICAL As String
Public FILLFORMAT_TILING_MIRROR_TYPE_BOTH As String

Sub Initialize()
	FILLFORMAT_PATTERN_NONE = 255
	FILLFORMAT_PATTERN_SOLID = 1
	FILLFORMAT_PATTERN_5_PERCENT = 196
	FILLFORMAT_PATTERN_50_PERCENT = 197
	FILLFORMAT_PATTERN_LIGHT_DOWNWARD_DIAGONAL = 198
	FILLFORMAT_PATTERN_LIGHT_VERTICAL = 199
	FILLFORMAT_PATTERN_DASHED_DOWNWARD_DIAGONAL = 200
	FILLFORMAT_PATTERN_ZIG_ZAG = 201
	FILLFORMAT_PATTERN_DIVOT = 202
	FILLFORMAT_PATTERN_SMALL_GRID = 203
	FILLFORMAT_PATTERN_10_PERCENT = 204
	FILLFORMAT_PATTERN_60_PERCENT = 205
	FILLFORMAT_PATTERN_LIGHT_UPWARD_DIAGONAL = 206
	FILLFORMAT_PATTERN_LIGHT_HORIZONTAL = 207
	FILLFORMAT_PATTERN_DASHED_UPWARD_DIAGONAL = 208
	FILLFORMAT_PATTERN_WAVE = 209
	FILLFORMAT_PATTERN_DOTTED_GRID = 210
	FILLFORMAT_PATTERN_LARGE_GRID = 211
	FILLFORMAT_PATTERN_20_PERCENT = 212
	FILLFORMAT_PATTERN_70_PERCENT = 213
	FILLFORMAT_PATTERN_DARK_DOWNWARD_DIAGONAL = 214
	FILLFORMAT_PATTERN_NARROW_VERTICAL = 215
	FILLFORMAT_PATTERN_DASHED_HORIZONTAL = 216
	FILLFORMAT_PATTERN_DIAGONAL_BRICK = 217
	FILLFORMAT_PATTERN_DOTTED_DIAMOND = 218
	FILLFORMAT_PATTERN_SMALL_CHECKER_BOARD = 219
	FILLFORMAT_PATTERN_25_PERCENT = 220
	FILLFORMAT_PATTERN_75_PERCENT = 221
	FILLFORMAT_PATTERN_DARK_UPWARD_DIAGONAL = 222
	FILLFORMAT_PATTERN_NARROW_HORIZONTAL = 223
	FILLFORMAT_PATTERN_DASHED_VERTICAL = 224
	FILLFORMAT_PATTERN_HORIZONTAL_BRICK = 225
	FILLFORMAT_PATTERN_SHINGLE = 226
	FILLFORMAT_PATTERN_LARGE_CHECKER_BOARD = 227
	FILLFORMAT_PATTERN_30_PERCENT = 228
	FILLFORMAT_PATTERN_80_PERCENT = 229
	FILLFORMAT_PATTERN_WIDE_DOWNWARD_DIAGONAL = 230
	FILLFORMAT_PATTERN_DARK_VERTICAL = 231
	FILLFORMAT_PATTERN_SMALL_CONFETTI = 232
	FILLFORMAT_PATTERN_WEAVE = 233
	FILLFORMAT_PATTERN_TRELLIS = 234
	FILLFORMAT_PATTERN_OUTLINED_DIAMOND = 235
	FILLFORMAT_PATTERN_40_PERCENT = 236
	FILLFORMAT_PATTERN_90_PERCENT = 237
	FILLFORMAT_PATTERN_WIDE_UPWARD_DIAGONAL = 238
	FILLFORMAT_PATTERN_DARK_HORIZONTAL = 239
	FILLFORMAT_PATTERN_LARGE_CONFETTI = 240
	FILLFORMAT_PATTERN_PLAID = 241
	FILLFORMAT_PATTERN_SPHERE = 242
	FILLFORMAT_PATTERN_SOLID_DIAMOND = 243
	FILLFORMAT_GRADIENT_FILL_DEFAULT = 0
	FILLFORMAT_GRADIENT_FILL_EARLY_SUNSET = 1
	FILLFORMAT_GGRADIENT_FILL_LATE_SUNSET = 2
	FILLFORMAT_GRADIENT_FILL_NIGHTFALL = 3
	FILLFORMAT_GRADIENT_FILL_DAYBREAK = 4
	FILLFORMAT_GRADIENT_FILL_HORIZON = 5
	FILLFORMAT_GRADIENT_FILL_DESERT = 6
	FILLFORMAT_GRADIENT_FILL_OCEAN = 7
	FILLFORMAT_GRADIENT_FILL_CALM_WATER = 8
	FILLFORMAT_GRADIENT_FILL_FIRE = 9
	FILLFORMAT_GRADIENT_FILL_FOG = 10
	FILLFORMAT_GRADIENT_FILL_MOSS = 11
	FILLFORMAT_GRADIENT_FILL_PEACOCK = 12
	FILLFORMAT_GRADIENT_FILL_WHEAT = 13
	FILLFORMAT_GRADIENT_FILL_PARCHMENT = 14
	FILLFORMAT_GRADIENT_FILL_MAHOGANY = 15
	FILLFORMAT_GRADIENT_FILL_RAINBOW = 16
	FILLFORMAT_GRADIENT_FILL_RAINBOW_II = 17
	FILLFORMAT_GRADIENT_FILL_GOLD = 18
	FILLFORMAT_GRADIENT_FILL_GOLD_II = 19
	FILLFORMAT_GRADIENT_FILL_BRASS = 20
	FILLFORMAT_GRADIENT_FILL_CHROME = 21
	FILLFORMAT_GRADIENT_FILL_CHROME_II = 22
	FILLFORMAT_GRADIENT_FILL_SILVER = 23
	FILLFORMAT_GRADIENT_FILL_SAPPHIRE = 24
	FILLFORMAT_GRADIENT_TYPE_LINEAR = 0
	FILLFORMAT_GRADIENT_TYPE_RADIAL = 1
	FILLFORMAT_GRADIENT_TYPE_RECTANGULAR = 2
	FILLFORMAT_GRADIENT_TYPE_PATH = 3
	FILLFORMAT_GRADIENT_DIRECTION_LINEAR_DIAGONAL_45_DEGREES = 45
	FILLFORMAT_GRADIENT_DIRECTION_LINEAR_DOWN_90_DEGREES = 90
	FILLFORMAT_GRADIENT_DIRECTION_LINEAR_DIAGONAL_135_DEGREES = 135
	FILLFORMAT_GRADIENT_DIRECTION_LINEAR_RIGHT_0_DEGREES = 0
	FILLFORMAT_GRADIENT_DIRECTION_LINEAR_LEFT_180_DEGREES = 180
	FILLFORMAT_GRADIENT_DIRECTION_LINEAR_DIAGONAL_315_DEGREES = 315
	FILLFORMAT_GRADIENT_DIRECTION_LINEAR_UP_270_DEGREES = 270
	FILLFORMAT_GRADIENT_DIRECTION_LINEAR_DIAGONAL_225_DEGREES = 225
	FILLFORMAT_GRADIENT_DIRECTION_FROM_CORNER_UPPER_LEFT_TO_BOTTOM_RIGHT = 0
	FILLFORMAT_GRADIENT_DIRECTION_FROM_CORNER_UPPER_RIGHT_TO_BOTTOM_LEFT = 1
	FILLFORMAT_GRADIENT_DIRECTION_FROM_CENTER = 2
	FILLFORMAT_GRADIENT_DIRECTION_FROM_CORNER_BOTTOM_LEFT_TO_UPPER_RIGHT = 3
	FILLFORMAT_GRADIENT_DIRECTION_FROM_CORNER_BOTTOM_RIGHT_TO_UPPER_LEFT = 4
	FILLFORMAT_TEXTURE_PAPYRUS = 0
	FILLFORMAT_TEXTURE_CANVAS = 1
	FILLFORMAT_TEXTURE_DENIM = 2
	FILLFORMAT_TEXTURE_WOVEN_MAT = 3
	FILLFORMAT_TEXTURE_WATER_DROPLETS = 4
	FILLFORMAT_TEXTURE_PAPER_BAG = 5
	FILLFORMAT_TEXTURE_FISH_FOSIL = 6
	FILLFORMAT_TEXTURE_SAND = 7
	FILLFORMAT_TEXTURE_GREEN_MARBLE = 8
	FILLFORMAT_TEXTURE_WHITE_MARBLE = 9
	FILLFORMAT_TEXTURE_BROWN_MARBLE = 10
	FILLFORMAT_TEXTURE_GRANITE = 11
	FILLFORMAT_TEXTURE_NEWSPRINT = 12
	FILLFORMAT_TEXTURE_RECYCLED_PAPER = 13
	FILLFORMAT_TEXTURE_PARCHMENT = 14
	FILLFORMAT_TEXTURE_STATIONERY = 15
	FILLFORMAT_TEXTURE_BLUE_TISSUE_PAPER = 16
	FILLFORMAT_TEXTURE_PINK_TISSUE_PAPER = 17
	FILLFORMAT_TEXTURE_PURPLE_MESH = 18
	FILLFORMAT_TEXTURE_BOUQUET = 19
	FILLFORMAT_TEXTURE_CORK = 20
	FILLFORMAT_TEXTURE_WALNUT = 21
	FILLFORMAT_TEXTURE_OAK = 22
	FILLFORMAT_TEXTURE_MEDIUM_WOOD = 23
	FILLFORMAT_TILING_ALIGNMENT_TOP_LEFT = "tl"
	FILLFORMAT_TILING_ALIGNMENT_TOP = "t"
	FILLFORMAT_TILING_ALIGNMENT_TOP_RIGHT = "tr"
	FILLFORMAT_TILING_ALIGNMENT_LEFT = "l"
	FILLFORMAT_TILING_ALIGNMENT_CENTER = "ctr"
	FILLFORMAT_TILING_ALIGNMENT_RIGHT = "r"
	FILLFORMAT_TILING_ALIGNMENT_BOTTOM_LEFT = "bl"
	FILLFORMAT_TILING_ALIGNMENT_BOTTOM = "b"
	FILLFORMAT_TILING_ALIGNMENT_BOTTOM_RIGHT = "br"
	FILLFORMAT_TILING_MIRROR_TYPE_NONE = "none"
	FILLFORMAT_TILING_MIRROR_TYPE_HORIZONTAL = "x"
	FILLFORMAT_TILING_MIRROR_TYPE_VERTICAL = "y"
	FILLFORMAT_TILING_MIRROR_TYPE_BOTH = "xy"
End Sub
