Attribute VB_Name = "Format3D"
Public FORMAT3D_BEVEL_NONE As String
Public FORMAT3D_BEVEL_CIRCLE As String
Public FORMAT3D_BEVEL_RELAXED_INSET As String
Public FORMAT3D_BEVEL_CROSS As String
Public FORMAT3D_BEVEL_COOL_SLANT As String
Public FORMAT3D_BEVEL_ANGLE As String
Public FORMAT3D_BEVEL_SOFT_ROUND As String
Public FORMAT3D_BEVEL_CONVEX As String
Public FORMAT3D_BEVEL_SLOPE As String
Public FORMAT3D_BEVEL_DIVOT As String
Public FORMAT3D_BEVEL_RIBLET As String
Public FORMAT3D_BEVEL_HARD_EDGE As String
Public FORMAT3D_BEVEL_ART_DECO As String
Public FORMAT3D_MATERIAL_NONE As String
Public FORMAT3D_MATERIAL_MATTE As String
Public FORMAT3D_MATERIAL_WARM_MATTE As String
Public FORMAT3D_MATERIAL_PLASTIC As String
Public FORMAT3D_MATERIAL_METAL As String
Public FORMAT3D_MATERIAL_DARK_EDGE As String
Public FORMAT3D_MATERIAL_SOFT_EDGE As String
Public FORMAT3D_MATERIAL_FLAT As String
Public FORMAT3D_MATERIAL_WIREFRAME As String
Public FORMAT3D_MATERIAL_POWDER As String
Public FORMAT3D_MATERIAL_TRANSLUCENT_POWDER As String
Public FORMAT3D_MATERIAL_CLEAR As String
Public FORMAT3D_LIGHTING_NONE As String
Public FORMAT3D_LIGHTING_THREE_POINT As String
Public FORMAT3D_LIGHTING_BALANCE As String
Public FORMAT3D_LIGHTING_SOFT As String
Public FORMAT3D_LIGHTING_HARSH As String
Public FORMAT3D_LIGHTING_FLOOD As String
Public FORMAT3D_LIGHTING_CONTRASTING As String
Public FORMAT3D_LIGHTING_MORNING As String
Public FORMAT3D_LIGHTING_SUNRISE As String
Public FORMAT3D_LIGHTING_SUNSET As String
Public FORMAT3D_LIGHTING_CHILLY As String
Public FORMAT3D_LIGHTING_FREEZING As String
Public FORMAT3D_LIGHTING_FLAT As String
Public FORMAT3D_LIGHTING_TWO_POINT As String
Public FORMAT3D_LIGHTING_GLOW As String
Public FORMAT3D_LIGHTING_BRIGHT_ROOM As String


Sub Initialize()
	FORMAT3D_BEVEL_NONE = "none"
	FORMAT3D_BEVEL_CIRCLE = "circle"
	FORMAT3D_BEVEL_RELAXED_INSET = "relaxedInset"
	FORMAT3D_BEVEL_CROSS = "cross"
	FORMAT3D_BEVEL_COOL_SLANT = "coolSlant"
	FORMAT3D_BEVEL_ANGLE = "angle"
	FORMAT3D_BEVEL_SOFT_ROUND = "softRound"
	FORMAT3D_BEVEL_CONVEX = "convex"
	FORMAT3D_BEVEL_SLOPE = "slope"
	FORMAT3D_BEVEL_DIVOT = "divot"
	FORMAT3D_BEVEL_RIBLET = "riblet"
	FORMAT3D_BEVEL_HARD_EDGE = "hardEdge"
	FORMAT3D_BEVEL_ART_DECO = "artDeco"
	FORMAT3D_MATERIAL_NONE = "none"
	FORMAT3D_MATERIAL_MATTE = "matte"
	FORMAT3D_MATERIAL_WARM_MATTE = "warmMatte"
	FORMAT3D_MATERIAL_PLASTIC = "plastic"
	FORMAT3D_MATERIAL_METAL = "metal"
	FORMAT3D_MATERIAL_DARK_EDGE = "dkEdge"
	FORMAT3D_MATERIAL_SOFT_EDGE= "softEdge"
	FORMAT3D_MATERIAL_FLAT = "flat"
	FORMAT3D_MATERIAL_WIREFRAME = "legacyWireframe"
	FORMAT3D_MATERIAL_POWDER = "powder"
	FORMAT3D_MATERIAL_TRANSLUCENT_POWDER = "translucentPowder"
	FORMAT3D_MATERIAL_CLEAR = "clear"
	FORMAT3D_LIGHTING_NONE = "none"
	FORMAT3D_LIGHTING_THREE_POINT = "threePt"
	FORMAT3D_LIGHTING_BALANCE = "balanced"
	FORMAT3D_LIGHTING_SOFT = "soft"
	FORMAT3D_LIGHTING_HARSH = "harsh"
	FORMAT3D_LIGHTING_FLOOD = "flood"
	FORMAT3D_LIGHTING_CONTRASTING = "contrasting"
	FORMAT3D_LIGHTING_MORNING = "morning"
	FORMAT3D_LIGHTING_SUNRISE = "sunrise"
	FORMAT3D_LIGHTING_SUNSET = "sunset"
	FORMAT3D_LIGHTING_CHILLY = "chilly"
	FORMAT3D_LIGHTING_FREEZING = "freezing"
	FORMAT3D_LIGHTING_FLAT = "flat"
	FORMAT3D_LIGHTING_TWO_POINT = "twoPt"
	FORMAT3D_LIGHTING_GLOW = "glow"
	FORMAT3D_LIGHTING_BRIGHT_ROOM = "brightRoom"
End Sub
