Attribute VB_Name = "Header"
Public HEADER_POSITION_LEFT As String
Public HEADER_POSITION_CENTER As String
Public HEADER_POSITION_RIGHT As String

Sub Initialize()
	HEADER_POSITION_LEFT = "L"
	HEADER_POSITION_CENTER = "C"
	HEADER_POSITION_RIGHT = "R"
End Sub
