Attribute VB_Name = "LineStyleFormat"
Public LINESTYLEFORMAT_COMPOUND_TYPE_SIMPLE As String
Public LINESTYLEFORMAT_COMPOUND_TYPE_DOUBLE As String
Public LINESTYLEFORMAT_COMPOUND_TYPE_THICK_THIN As String
Public LINESTYLEFORMAT_COMPOUND_TYPE_THIN_THICK As String
Public LINESTYLEFORMAT_COMPOUND_TYPE_TRIPLE As String
Public LINESTYLEFORMAT_DASH_TYPE_SOLID As String
Public LINESTYLEFORMAT_DASH_TYPE_ROUND_DOT As String
Public LINESTYLEFORMAT_DASH_TYPE_SQUARE_DOT As String
Public LINESTYLEFORMAT_DASH_TYPE_DASH As String
Public LINESTYLEFORMAT_DASH_TYPE_DASH_DOT As String
Public LINESTYLEFORMAT_DASH_TYPE_LONG_DASH As String
Public LINESTYLEFORMAT_DASH_TYPE_LONG_DASH_DOT As String
Public LINESTYLEFORMAT_DASH_TYPE_LONG_DASH_DOT_DOT As String
Public LINESTYLEFORMAT_CAP_TYPE_SQUARE As String
Public LINESTYLEFORMAT_CAP_TYPE_ROUND As String
Public LINESTYLEFORMAT_CAP_TYPE_FLAT As String
Public LINESTYLEFORMAT_JOIN_TYPE_ROUND As String
Public LINESTYLEFORMAT_JOIN_TYPE_BEVEL As String
Public LINESTYLEFORMAT_JOIN_TYPE_MITER As String
Public LINESTYLEFORMAT_ARROW_TYPE_NONE As String
Public LINESTYLEFORMAT_ARROW_TYPE_TRIANGLE As String
Public LINESTYLEFORMAT_ARROW_TYPE_OPEN As String
Public LINESTYLEFORMAT_ARROW_TYPE_STEALTH As String
Public LINESTYLEFORMAT_ARROW_TYPE_DIAMOND As String
Public LINESTYLEFORMAT_ARROW_TYPE_OVAL As String

Sub Initialize()
    LINESTYLEFORMAT_COMPOUND_TYPE_NONE = "none"
    LINESTYLEFORMAT_COMPOUND_TYPE_SIMPLE = "sng"
    LINESTYLEFORMAT_COMPOUND_TYPE_DOUBLE = "dbl"
    LINESTYLEFORMAT_COMPOUND_TYPE_THICK_THIN = "thickThin"
    LINESTYLEFORMAT_COMPOUND_TYPE_THIN_THICK = "thinThick"
    LINESTYLEFORMAT_COMPOUND_TYPE_TRIPLE = "tri"
    LINESTYLEFORMAT_DASH_TYPE_SOLID = "solid"
    LINESTYLEFORMAT_DASH_TYPE_ROUND_DOT = "sysDot"
    LINESTYLEFORMAT_DASH_TYPE_SQUARE_DOT = "sysDash"
    LINESTYLEFORMAT_DASH_TYPE_DASH = "dash"
    LINESTYLEFORMAT_DASH_TYPE_DASH_DOT = "dashDot"
    LINESTYLEFORMAT_DASH_TYPE_LONG_DASH = "lgDash"
    LINESTYLEFORMAT_DASH_TYPE_LONG_DASH_DOT = "lgDashDot"
    LINESTYLEFORMAT_DASH_TYPE_LONG_DASH_DOT_DOT = "lgDashDotDot"
    LINESTYLEFORMAT_CAP_TYPE_SQUARE = "sq"
    LINESTYLEFORMAT_CAP_TYPE_ROUND = "rnd"
    LINESTYLEFORMAT_CAP_TYPE_FLAT = "flat"
    LINESTYLEFORMAT_JOIN_TYPE_ROUND = "round"
    LINESTYLEFORMAT_JOIN_TYPE_BEVEL = "bevel"
    LINESTYLEFORMAT_JOIN_TYPE_MITER = "miter"
    LINESTYLEFORMAT_ARROW_TYPE_NONE = "none"
    LINESTYLEFORMAT_ARROW_TYPE_TRIANGLE = "triangle"
    LINESTYLEFORMAT_ARROW_TYPE_OPEN = "arrow"
    LINESTYLEFORMAT_ARROW_TYPE_STEALTH = "stealth"
    LINESTYLEFORMAT_ARROW_TYPE_DIAMOND = "diamond"
    LINESTYLEFORMAT_ARROW_TYPE_OVAL = "oval"
End Sub

