Attribute VB_Name = "PageSetup"
Public PAGESETUP_ORIENTATION_PORTRAIT As String
Public PAGESETUP_ORIENTATION_LANDSCAPE As String
Public PAGESETUP_PAPER_SIZE_CUSTOM As Long
Public PAGESETUP_PAPER_SIZE_LETTER As Long
Public PAGESETUP_PAPER_SIZE_LETTER_SMALL As Long
Public PAGESETUP_PAPER_SIZE_TABLOID As Long
Public PAGESETUP_PAPER_SIZE_LEDGER As Long
Public PAGESETUP_PAPER_SIZE_LEGAL As Long
Public PAGESETUP_PAPER_SIZE_STATEMENT As Long
Public PAGESETUP_PAPER_SIZE_EXECUTIVE As Long
Public PAGESETUP_PAPER_SIZE_A3 As Long
Public PAGESETUP_PAPER_SIZE_A4 As Long
Public PAGESETUP_PAPER_SIZE_A4_SMALL As Long
Public PAGESETUP_PAPER_SIZE_A5 As Long
Public PAGESETUP_PAPER_SIZE_B4 As Long
Public PAGESETUP_PAPER_SIZE_B5_JIS As Long
Public PAGESETUP_PAPER_SIZE_FOLIO_PAPER As Long
Public PAGESETUP_PAPER_SIZE_QUARTO_PAPER As Long
Public PAGESETUP_PAPER_SIZE_STANDARD_PAPER_10_BY_14 As Long
Public PAGESETUP_PAPER_SIZE_STANDARD_PAPER_11_BY_17 As Long
Public PAGESETUP_PAPER_SIZE_NOTE_PAPER As Long
Public PAGESETUP_PAPER_SIZE_ENVELOPE_9 As Long
Public PAGESETUP_PAPER_SIZE_ENVELOPE_10 As Long
Public PAGESETUP_PAPER_SIZE_ENVELOPE_11 As Long
Public PAGESETUP_PAPER_SIZE_ENVELOPE_12 As Long
Public PAGESETUP_PAPER_SIZE_ENVELOPE_14 As Long
Public PAGESETUP_PAPER_SIZE_C_PAPER As Long
Public PAGESETUP_PAPER_SIZE_D_PAPER As Long
Public PAGESETUP_PAPER_SIZE_E_PAPER As Long
Public PAGESETUP_PAPER_SIZE_ENVELOPE_DL As Long
Public PAGESETUP_PAPER_SIZE_ENVELOPE_C5 As Long
Public PAGESETUP_PAPER_SIZE_ENVELOPE_C3 As Long
Public PAGESETUP_PAPER_SIZE_ENVELOPE_C4 As Long
Public PAGESETUP_PAPER_SIZE_ENVELOPE_C6 As Long
Public PAGESETUP_PAPER_SIZE_ENVELOPE_C65 As Long
Public PAGESETUP_PAPER_SIZE_ENVELOPE_B4 As Long
Public PAGESETUP_PAPER_SIZE_ENVELOPE_B5 As Long
Public PAGESETUP_PAPER_SIZE_ENVELOPE_B6 As Long
Public PAGESETUP_PAPER_SIZE_ENVELOPE_ITALY As Long
Public PAGESETUP_PAPER_SIZE_ENVELOPE_MONARCH As Long
Public PAGESETUP_PAPER_SIZE_ENVELOPE_6_3PER4 As Long
Public PAGESETUP_PAPER_SIZE_US_STANDARD_FANFOLD As Long
Public PAGESETUP_PAPER_SIZE_GERMAN_STANDARD_FANFOLD As Long
Public PAGESETUP_PAPER_SIZE_GERMAN_LEGAL_FANFOLD As Long
Public PAGESETUP_PAPER_SIZE_B4_ISO As Long
Public PAGESETUP_PAPER_SIZE_JAPANESE_DOUBLE_POSTCARD As Long
Public PAGESETUP_PAPER_SIZE_STANDARD_PAPER_9_BY_11 As Long
Public PAGESETUP_PAPER_SIZE_STANDARD_PAPER_10_BY_11 As Long
Public PAGESETUP_PAPER_SIZE_STANDARD_PAPER_15_BY_11 As Long
Public PAGESETUP_PAPER_SIZE_ENVELOPE_INVITE As Long
Public PAGESETUP_PAPER_SIZE_LETTER_EXTRA_PAPER As Long
Public PAGESETUP_PAPER_SIZE_LEGAL_EXTRA_PAPER As Long
Public PAGESETUP_PAPER_SIZE_TABLOID_EXTRA_PAPER As Long
Public PAGESETUP_PAPER_SIZE_A4_EXTRA_PAPER As Long
Public PAGESETUP_PAPER_SIZE_LETTER_TRANSVERSE_PAPER As Long
Public PAGESETUP_PAPER_SIZE_A4_TRANSVERSE_PAPER As Long
Public PAGESETUP_PAPER_SIZE_LETTER_EXTRA_TRANSVERSE_PAPER As Long
Public PAGESETUP_PAPER_SIZE_SUPER_A_PER_SUPER_A_PER_A4 As Long
Public PAGESETUP_PAPER_SIZE_SUPER_B_PER_SUPER_B_PER_A3 As Long
Public PAGESETUP_PAPER_SIZE_LETTER_PLUS_PAPER As Long
Public PAGESETUP_PAPER_SIZE_A4_PLUS_PAPER As Long
Public PAGESETUP_PAPER_SIZE_A5_TRANSVERSE_PAPER As Long
Public PAGESETUP_PAPER_SIZE_B5_JIS_TRANSVERSE_PAPER As Long
Public PAGESETUP_PAPER_SIZE_A3_EXTRA_PAPER As Long
Public PAGESETUP_PAPER_SIZE_A5_EXTRA_PAPER As Long
Public PAGESETUP_PAPER_SIZE_B5_EXTRA_PAPER_ISO As Long
Public PAGESETUP_PAPER_SIZE_A2_PAPER As Long
Public PAGESETUP_PAPER_SIZE_A3_TRANSVERSE_PAPER As Long
Public PAGESETUP_PAPER_SIZE_A3_EXTRA_TRANSVERSE_PAPER As Long
Public PAGESETUP_PAPER_SIZE_A6 As Long
Public PAGESETUP_PAPER_SIZE_B5_ISO As Long
Public PAGESETUP_PAPER_SIZE_DOUBLE_POST_CARD As Long
Public PAGESETUP_PAPER_SIZE_POST_CARD As Long
Public PAGESETUP_PAPER_SIZE_16K As Long
Public PAGESETUP_COMMENTS_NONE As Long
Public PAGESETUP_COMMENTS_AT_END_OF_SHEET As Long
Public PAGESETUP_COMMENTS_AS_DISPLAYED_ON_SHEET As Long
Public PAGESETUP_PAGE_ORDER_DOWN_THEN_OVER As Long
Public PAGESETUP_PAGE_ORDER_OVER_THEN_DOWN As Long

Sub Initialize()
	PAGESETUP_ORIENTATION_PORTRAIT = "Portrait"
	PAGESETUP_ORIENTATION_LANDSCAPE = "Landscape"
	PAGESETUP_PAPER_SIZE_CUSTOM = 0
	PAGESETUP_PAPER_SIZE_LETTER = 1
	PAGESETUP_PAPER_SIZE_LETTER_SMALL = 2
	PAGESETUP_PAPER_SIZE_TABLOID = 3
	PAGESETUP_PAPER_SIZE_LEDGER = 4
	PAGESETUP_PAPER_SIZE_LEGAL = 5
	PAGESETUP_PAPER_SIZE_STATEMENT = 6
	PAGESETUP_PAPER_SIZE_EXECUTIVE = 7
	PAGESETUP_PAPER_SIZE_A3 = 8
	PAGESETUP_PAPER_SIZE_A4 = 9
	PAGESETUP_PAPER_SIZE_A4_SMALL = 10
	PAGESETUP_PAPER_SIZE_A5 = 11
	PAGESETUP_PAPER_SIZE_B4 = 12
	PAGESETUP_PAPER_SIZE_B5_JIS = 13
	PAGESETUP_PAPER_SIZE_FOLIO_PAPER = 14
	PAGESETUP_PAPER_SIZE_QUARTO_PAPER = 15
	PAGESETUP_PAPER_SIZE_STANDARD_PAPER_10_BY_14 = 16
	PAGESETUP_PAPER_SIZE_STANDARD_PAPER_11_BY_17 = 17
	PAGESETUP_PAPER_SIZE_NOTE_PAPER = 18
	PAGESETUP_PAPER_SIZE_ENVELOPE_9 = 19
	PAGESETUP_PAPER_SIZE_ENVELOPE_10 = 20
	PAGESETUP_PAPER_SIZE_ENVELOPE_11 = 21
	PAGESETUP_PAPER_SIZE_ENVELOPE_12 = 22
	PAGESETUP_PAPER_SIZE_ENVELOPE_14 = 23
	PAGESETUP_PAPER_SIZE_C_PAPER = 24
	PAGESETUP_PAPER_SIZE_D_PAPER = 25
	PAGESETUP_PAPER_SIZE_E_PAPER = 26
	PAGESETUP_PAPER_SIZE_ENVELOPE_DL = 27
	PAGESETUP_PAPER_SIZE_ENVELOPE_C5 = 28
	PAGESETUP_PAPER_SIZE_ENVELOPE_C3 = 29
	PAGESETUP_PAPER_SIZE_ENVELOPE_C4 = 30
	PAGESETUP_PAPER_SIZE_ENVELOPE_C6 = 31
	PAGESETUP_PAPER_SIZE_ENVELOPE_C65 = 32
	PAGESETUP_PAPER_SIZE_ENVELOPE_B4 = 33
	PAGESETUP_PAPER_SIZE_ENVELOPE_B5 = 34
	PAGESETUP_PAPER_SIZE_ENVELOPE_B6 = 35
	PAGESETUP_PAPER_SIZE_ENVELOPE_ITALY = 36
	PAGESETUP_PAPER_SIZE_ENVELOPE_MONARCH = 37
	PAGESETUP_PAPER_SIZE_ENVELOPE_6_3PER4 = 38
	PAGESETUP_PAPER_SIZE_US_STANDARD_FANFOLD = 39
	PAGESETUP_PAPER_SIZE_GERMAN_STANDARD_FANFOLD = 40
	PAGESETUP_PAPER_SIZE_GERMAN_LEGAL_FANFOLD = 41
	PAGESETUP_PAPER_SIZE_B4_ISO = 42
	PAGESETUP_PAPER_SIZE_JAPANESE_DOUBLE_POSTCARD = 43
	PAGESETUP_PAPER_SIZE_STANDARD_PAPER_9_BY_11 = 44
	PAGESETUP_PAPER_SIZE_STANDARD_PAPER_10_BY_11 = 45
	PAGESETUP_PAPER_SIZE_STANDARD_PAPER_15_BY_11 = 46
	PAGESETUP_PAPER_SIZE_ENVELOPE_INVITE = 47
	PAGESETUP_PAPER_SIZE_LETTER_EXTRA_PAPER = 50
	PAGESETUP_PAPER_SIZE_LEGAL_EXTRA_PAPER = 51
	PAGESETUP_PAPER_SIZE_TABLOID_EXTRA_PAPER = 52
	PAGESETUP_PAPER_SIZE_A4_EXTRA_PAPER = 53
	PAGESETUP_PAPER_SIZE_LETTER_TRANSVERSE_PAPER = 54
	PAGESETUP_PAPER_SIZE_A4_TRANSVERSE_PAPER = 55
	PAGESETUP_PAPER_SIZE_LETTER_EXTRA_TRANSVERSE_PAPER = 56
	PAGESETUP_PAPER_SIZE_SUPER_A_PER_SUPER_A_PER_A4 = 57
	PAGESETUP_PAPER_SIZE_SUPER_B_PER_SUPER_B_PER_A3 = 58
	PAGESETUP_PAPER_SIZE_LETTER_PLUS_PAPER = 59
	PAGESETUP_PAPER_SIZE_A4_PLUS_PAPER = 60
	PAGESETUP_PAPER_SIZE_A5_TRANSVERSE_PAPER = 61
	PAGESETUP_PAPER_SIZE_B5_JIS_TRANSVERSE_PAPER = 62
	PAGESETUP_PAPER_SIZE_A3_EXTRA_PAPER = 63
	PAGESETUP_PAPER_SIZE_A5_EXTRA_PAPER = 64
	PAGESETUP_PAPER_SIZE_B5_EXTRA_PAPER_ISO = 65
	PAGESETUP_PAPER_SIZE_A2_PAPER = 66
	PAGESETUP_PAPER_SIZE_A3_TRANSVERSE_PAPER = 67
	PAGESETUP_PAPER_SIZE_A3_EXTRA_TRANSVERSE_PAPER = 68
	PAGESETUP_PAPER_SIZE_A6 = 70
	PAGESETUP_PAPER_SIZE_B5_ISO = 119
	PAGESETUP_PAPER_SIZE_DOUBLE_POST_CARD = 120
	PAGESETUP_PAPER_SIZE_POST_CARD = 121
	PAGESETUP_PAPER_SIZE_16K = 123
	PAGESETUP_COMMENTS_NONE = 0
	PAGESETUP_COMMENTS_AT_END_OF_SHEET = 1
	PAGESETUP_COMMENTS_AS_DISPLAYED_ON_SHEET = 2
	PAGESETUP_PAGE_ORDER_DOWN_THEN_OVER = 0
	PAGESETUP_PAGE_ORDER_OVER_THEN_DOWN = 1
End Sub
