Attribute VB_Name = "Pattern"
Public PATTERN_PATTERN_NONE As Long
Public PATTERN_PATTERN_SOLID As Long
Public PATTERN_PATTERN_50PERCENT_GRAY As Long
Public PATTERN_PATTERN_75PERCENT_GRAY As Long
Public PATTERN_PATTERN_25PERCENT_GRAY As Long
Public PATTERN_PATTERN_HORIZONTAL_STRIPE As Long
Public PATTERN_PATTERN_VERTICAL_STRIPE As Long
Public PATTERN_PATTERN_REVERSE_DIAGONAL_STRIPE As Long
Public PATTERN_PATTERN_DIAGONAL_STRIPE As Long
Public PATTERN_PATTERN_DIAGONAL_CROSSHATCH As Long
Public PATTERN_PATTERN_THICK_DIAGONAL_CROSSHATCH As Long
Public PATTERN_PATTERN_THIN_HORIZONTAL_STRIPE As Long
Public PATTERN_PATTERN_THIN_VERTICAL_STRIPE As Long
Public PATTERN_PATTERN_THIN_REVERSE_DIAGONAL_STRIPE As Long
Public PATTERN_PATTERN_THIN_DIAGONAL_STRIPE As Long
Public PATTERN_PATTERN_THIN_HORIZONTAL_CROSSHATCH As Long
Public PATTERN_PATTERN_THIN_DIAGONAL_CROSSHATCH As Long
Public PATTERN_PATTERN_12PERCENT_GRAY As Long
Public PATTERN_PATTERN_6PERCENT_GRAY As Long
	

Sub Initialize()
	PATTERN_PATTERN_NONE = 0
	PATTERN_PATTERN_SOLID = 1
	PATTERN_PATTERN_50PERCENT_GRAY = 2
	PATTERN_PATTERN_75PERCENT_GRAY = 3
	PATTERN_PATTERN_25PERCENT_GRAY = 4
	PATTERN_PATTERN_HORIZONTAL_STRIPE = 5
	PATTERN_PATTERN_VERTICAL_STRIPE = 6
	PATTERN_PATTERN_REVERSE_DIAGONAL_STRIPE = 7
	PATTERN_PATTERN_DIAGONAL_STRIPE = 8
	PATTERN_PATTERN_DIAGONAL_CROSSHATCH = 9
	PATTERN_PATTERN_THICK_DIAGONAL_CROSSHATCH = 10
	PATTERN_PATTERN_THIN_HORIZONTAL_STRIPE = 11
	PATTERN_PATTERN_THIN_VERTICAL_STRIPE = 12
	PATTERN_PATTERN_THIN_REVERSE_DIAGONAL_STRIPE = 13
	PATTERN_PATTERN_THIN_DIAGONAL_STRIPE = 14
	PATTERN_PATTERN_THIN_HORIZONTAL_CROSSHATCH = 15
	PATTERN_PATTERN_THIN_DIAGONAL_CROSSHATCH = 16
	PATTERN_PATTERN_12PERCENT_GRAY = 17
	PATTERN_PATTERN_6PERCENT_GRAY = 18
End Sub
