Attribute VB_Name = "Table"
Public TABLE_MAX_ROWS_OFFICE_97_2003 As Long
Public TABLE_MAX_COLUMNS_OFFICE_97_2003 As Long
Public TABLE_MAX_ROWS As Long
Public TABLE_MAX_COLUMNS As Long
Public TABLE_LOOK_IN_FORMULAS As Long
Public TABLE_LOOK_IN_VALUES As Long
Public TABLE_LOOK_IN_COMMENTS As Long

Sub Initialize()
        TABLE_MAX_ROWS_OFFICE_97_2003 = 65536
        TABLE_MAX_COLUMNS_OFFICE_97_2003 = 256
        TABLE_MAX_ROWS = 1048576
        TABLE_MAX_COLUMNS = 16384
        TABLE_LOOK_IN_FORMULAS = 0
        TABLE_LOOK_IN_VALUES = 1
        TABLE_LOOK_IN_COMMENTS = 2
End Sub