Attribute VB_Name = "Theme"
Public THEME_THEME_OFFICE As String
Public THEME_THEME_APEX As String
Public THEME_THEME_ASPECT As String
Public THEME_THEME_CIVIC As String
Public THEME_THEME_CONCOURSE As String
Public THEME_THEME_EQUITY As String
Public THEME_THEME_FLOW As String
Public THEME_THEME_FOUNDRY As String
Public THEME_THEME_MEDIAN As String
Public THEME_THEME_METRO As String
Public THEME_THEME_MODULE As String
Public THEME_THEME_OPULENT As String
Public THEME_THEME_ORIEL As String
Public THEME_THEME_ORIGIN As String
Public THEME_THEME_PAPER As String
Public THEME_THEME_SOLSTICE As String
Public THEME_THEME_TECHNIC As String
Public THEME_THEME_TREK As String
Public THEME_THEME_URBAN As String
Public THEME_THEME_VERVE As String
Public THEME_THEME_COLORS_OFFICE As String
Public THEME_THEME_COLORS_GRAYSCALE As String
Public THEME_THEME_COLORS_APEX As String
Public THEME_THEME_COLORS_ASPECT As String
Public THEME_THEME_COLORS_CIVIC As String
Public THEME_THEME_COLORS_CONCOURSE As String
Public THEME_THEME_COLORS_EQUITY As String
Public THEME_THEME_COLORS_FLOW As String
Public THEME_THEME_COLORS_FOUNDRY As String
Public THEME_THEME_COLORS_MEDIAN As String
Public THEME_THEME_COLORS_METRO As String
Public THEME_THEME_COLORS_MODULE As String
Public THEME_THEME_COLORS_OPULENT As String
Public THEME_THEME_COLORS_ORIEL As String
Public THEME_THEME_COLORS_ORIGIN As String
Public THEME_THEME_COLORS_PAPER As String
Public THEME_THEME_COLORS_SOLSTICE As String
Public THEME_THEME_COLORS_TECHNIC As String
Public THEME_THEME_COLORS_TREK As String
Public THEME_THEME_COLORS_URBAN As String
Public THEME_THEME_COLORS_VERVE As String
Public THEME_THEME_FONTS_OFFICE As String
Public THEME_THEME_FONTS_OFFICE2 As String
Public THEME_THEME_FONTS_OFFICE_CLASSIC As String
Public THEME_THEME_FONTS_OFFICE_CLASSIC2 As String
Public THEME_THEME_FONTS_APEX As String
Public THEME_THEME_FONTS_ASPECT As String
Public THEME_THEME_FONTS_CIVIC As String
Public THEME_THEME_FONTS_CONCOURSE As String
Public THEME_THEME_FONTS_EQUITY As String
Public THEME_THEME_FONTS_FLOW As String
Public THEME_THEME_FONTS_FOUNDRY As String
Public THEME_THEME_FONTS_MEDIAN As String
Public THEME_THEME_FONTS_METRO As String
Public THEME_THEME_FONTS_MODULE As String
Public THEME_THEME_FONTS_OPULENT As String
Public THEME_THEME_FONTS_ORIEL As String
Public THEME_THEME_FONTS_ORIGIN As String
Public THEME_THEME_FONTS_PAPER As String
Public THEME_THEME_FONTS_SOLSTICE As String
Public THEME_THEME_FONTS_TECHNIC As String
Public THEME_THEME_FONTS_TREK As String
Public THEME_THEME_FONTS_URBAN As String
Public THEME_THEME_FONTS_VERVE As String
Public THEME_THEME_EFFECTS_OFFICE As String
Public THEME_THEME_EFFECTS_APEX As String
Public THEME_THEME_EFFECTS_ASPECT As String
Public THEME_THEME_EFFECTS_CIVIC As String
Public THEME_THEME_EFFECTS_CONCOURSE As String
Public THEME_THEME_EFFECTS_EQUITY As String
Public THEME_THEME_EFFECTS_FLOW As String
Public THEME_THEME_EFFECTS_FOUNDRY As String
Public THEME_THEME_EFFECTS_MEDIAN As String
Public THEME_THEME_EFFECTS_METRO As String
Public THEME_THEME_EFFECTS_MODULE As String
Public THEME_THEME_EFFECTS_OPULENT As String
Public THEME_THEME_EFFECTS_ORIEL As String
Public THEME_THEME_EFFECTS_ORIGIN As String
Public THEME_THEME_EFFECTS_PAPER As String
Public THEME_THEME_EFFECTS_SOLSTICE As String
Public THEME_THEME_EFFECTS_TECHNIC As String
Public THEME_THEME_EFFECTS_TREK As String
Public THEME_THEME_EFFECTS_URBAN As String
Public THEME_THEME_EFFECTS_VERVE As String

Sub Initialize()
	THEME_THEME_OFFICE = "Office Theme"
	THEME_THEME_APEX = "Apex"
	THEME_THEME_ASPECT = "Aspect"
	THEME_THEME_CIVIC = "Civic"
	THEME_THEME_CONCOURSE = "Concourse"
	THEME_THEME_EQUITY = "Equity"
	THEME_THEME_FLOW = "Flow"
	THEME_THEME_FOUNDRY = "Foundry"
	THEME_THEME_MEDIAN = "Median"
	THEME_THEME_METRO = "Metro"
	THEME_THEME_MODULE = "Module"
	THEME_THEME_OPULENT = "Opulent"
	THEME_THEME_ORIEL = "Oriel"
	THEME_THEME_ORIGIN = "Origin"
	THEME_THEME_PAPER = "Paper"
	THEME_THEME_SOLSTICE = "Solstice"
	THEME_THEME_TECHNIC = "Technic"
	THEME_THEME_TREK = "Trek"
	THEME_THEME_URBAN = "Urban"
	THEME_THEME_VERVE = "Verve"
	THEME_THEME_COLORS_OFFICE = "Office"
	THEME_THEME_COLORS_GRAYSCALE = "Grayscale"
	THEME_THEME_COLORS_APEX = "Apex"
	THEME_THEME_COLORS_ASPECT = "Aspect"
	THEME_THEME_COLORS_CIVIC = "Civic"
	THEME_THEME_COLORS_CONCOURSE = "Concourse"
	THEME_THEME_COLORS_EQUITY = "Equity"
	THEME_THEME_COLORS_FLOW = "Flow"
	THEME_THEME_COLORS_FOUNDRY = "Foundry"
	THEME_THEME_COLORS_MEDIAN = "Median"
	THEME_THEME_COLORS_METRO = "Metro"
	THEME_THEME_COLORS_MODULE = "Module"
	THEME_THEME_COLORS_OPULENT = "Opulent"
	THEME_THEME_COLORS_ORIEL = "Oriel"
	THEME_THEME_COLORS_ORIGIN = "Origin"
	THEME_THEME_COLORS_PAPER = "Paper"
	THEME_THEME_COLORS_SOLSTICE = "Solstice"
	THEME_THEME_COLORS_TECHNIC = "Technic"
	THEME_THEME_COLORS_TREK = "Trek"
	THEME_THEME_COLORS_URBAN = "Urban"
	THEME_THEME_COLORS_VERVE = "Verve"
	THEME_THEME_FONTS_OFFICE = "Office"
	THEME_THEME_FONTS_OFFICE2 = "Office 2"
	THEME_THEME_FONTS_OFFICE_CLASSIC = "Office Classic"
	THEME_THEME_FONTS_OFFICE_CLASSIC2 = "Office Classic 2"
	THEME_THEME_FONTS_APEX = "Apex"
	THEME_THEME_FONTS_ASPECT = "Aspect"
	THEME_THEME_FONTS_CIVIC = "Civic"
	THEME_THEME_FONTS_CONCOURSE = "Concourse"
	THEME_THEME_FONTS_EQUITY = "Equity"
	THEME_THEME_FONTS_FLOW = "Flow"
	THEME_THEME_FONTS_FOUNDRY = "Foundry"
	THEME_THEME_FONTS_MEDIAN = "Median"
	THEME_THEME_FONTS_METRO = "Metro"
	THEME_THEME_FONTS_MODULE = "Module"
	THEME_THEME_FONTS_OPULENT = "Opulent"
	THEME_THEME_FONTS_ORIEL = "Oriel"
	THEME_THEME_FONTS_ORIGIN = "Origin"
	THEME_THEME_FONTS_PAPER = "Paper"
	THEME_THEME_FONTS_SOLSTICE = "Solstice"
	THEME_THEME_FONTS_TECHNIC = "Technic"
	THEME_THEME_FONTS_TREK = "Trek"
	THEME_THEME_FONTS_URBAN = "Urban"
	THEME_THEME_FONTS_VERVE = "Verve"
	THEME_THEME_EFFECTS_OFFICE = "Office"
	THEME_THEME_EFFECTS_APEX = "Apex"
	THEME_THEME_EFFECTS_ASPECT = "Aspect"
	THEME_THEME_EFFECTS_CIVIC = "Civic"
	THEME_THEME_EFFECTS_CONCOURSE = "Concourse"
	THEME_THEME_EFFECTS_EQUITY = "Equity"
	THEME_THEME_EFFECTS_FLOW = "Flow"
	THEME_THEME_EFFECTS_FOUNDRY = "Foundry"
	THEME_THEME_EFFECTS_MEDIAN = "Median"
	THEME_THEME_EFFECTS_METRO = "Metro"
	THEME_THEME_EFFECTS_MODULE = "Module"
	THEME_THEME_EFFECTS_OPULENT = "Opulent"
	THEME_THEME_EFFECTS_ORIEL = "Oriel"
	THEME_THEME_EFFECTS_ORIGIN = "Origin"
	THEME_THEME_EFFECTS_PAPER = "Paper"
	THEME_THEME_EFFECTS_SOLSTICE = "Solstice"
	THEME_THEME_EFFECTS_TECHNIC = "Technic"
	THEME_THEME_EFFECTS_TREK = "Trek"
	THEME_THEME_EFFECTS_URBAN = "Urban"
	THEME_THEME_EFFECTS_VERVE = "Verve"
End Sub
